### ISSUE TITLE
Try catch error

### ISSUE THREAD

**Issue by cdchn1989** [Abhay2012/mysql-async-wrapper#1]
I am currently using your package, but when for example there is a "syntax error" in a query the catch does not capture the error but in the node console it shows the following error, the whole package works fine less when there is an error in the different queries

(node:11239) UnhandledPromiseRejectionWarning: TypeError: ER_PARSE_ERROR is not a function
    at Array.findIndex (<anonymous>)
    at BaseDatabase.<anonymous> (/opt/node/navis/server/node_modules/mysql-async-wrapper/dist/index.js:163:56)
    at Generator.next (<anonymous>)
    at /opt/node/navis/server/node_modules/mysql-async-wrapper/dist/index.js:24:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/node/navis/server/node_modules/mysql-async-wrapper/dist/index.js:20:12)
    at Query.queryString._connection.query (/opt/node/navis/server/node_modules/mysql-async-wrapper/dist/index.js:160:93)
    at Query.<anonymous> (/opt/node/navis/server/node_modules/mysql/lib/Connection.js:525:10)
    at Query._callback (/opt/node/navis/server/node_modules/mysql/lib/Connection.js:491:16)
    at Query.Sequence.end (/opt/node/navis/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
(node:11239) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11239) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

My node version is 10.19.0

My proyect is deployed with typescript version 3.5.3
----------------------------------------------------------------------------------------------------------------------------------
My db configuration file is:

import mysql from "mysql";
const BaseDatabase = require("mysql-async-wrapper").default;

  const pool = mysql.createPool({
    host: '127.0.0.1',
    user: 'root',
    password: '',
    database: 'my_db'
  })
const db = new BaseDatabase(pool);
export default db;

--------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------
my file controller is:

import { Request, Response} from 'express';
import Database from '../../db';
 
class ClientesController{

    public async obtenerClientes(req: Request, res: Response){
    let data=req['body'];
    let db = await Database.getConnection();
    try{
      let result_count = await db.executeQuery(`call pa_clientes_contar("${data['filtro']}")`);
      let result_data = await db.executeQuery(`call  pa_clientes_obtener_clientes(${data['numeroFila']},${data['tamanioPagina']},${data['filtro']})`);
      return res.status(200).json({data:result_count, data2: result_data});
    }catch(e){
      return res.status(500).json({message: 'Error al obtener los clientes',err:e});
    }finally{
      await db.close();
    }
  }

}
----------------------------------------------------------------------------------------------------------------------------
Really I have no idea what I do wrong or what is the problem.

Regards

**Comment by Abhay2012** [comment]
Hi, sorry for the late reply,
the first thing is getConnection line in ClientesController is outside the try block, so when there is an error while getting connection it won't go in the catch block and remains unhandled.

And yes there is an error in package executeQuery function and I've fixed it in 2.0.1 version please update the package 
    `npm install mysql-async-wrapper@latest`

Thanks for reporting the issue.

**Comment by Abhay2012** [comment]
I'm closing this issue as it is resolved in the latest version 2.0.1 @cdchn1989

**Comment by cdchn1989** [comment]
I tried your solution however needed that when capturing the error rollback, I finally decided to create my own mysql wrapper, thanks for your feddback.

Regards.

**Comment by Abhay2012** [comment]
Yes there is an issue in case of query error which I've fixed in a 2.0.1 now and its nice that you're creating your own wrapper and thanks once again for posting this issue
